version: '3'
services:

  proxy:
    image: "carbobot/proxy"
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    environment:
      - PUBLIC_HOST=localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/proxy/letsencrypt:/etc/letsencrypt
      - ./data/proxy/log:/var/log/proxy

  webapp:
    image: "carbobot/webapp"
    container_name: webapp
    hostname: webapp
    restart: unless-stopped
    environment:
      - DJANGO_DEV_SERVER=true
      - DJANGO_DEBUG=true
      - DJANGO_LOG_LEVEL=ERROR
      - WEBAPP_LOG_LEVEL=DEBUG
      - PUBLIC_HOST=http://localhost
      #- DJANGO_SECRET_KEY=
    ports:
      - "8080:8080"
    volumes:
      - ./data/webapp/data:/data
      - ./services/webapp/code:/code # For live code changes

  search_api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: carbo_search_api
    ports:
      - "3000:80"
    depends_on:
      - elasticsearch
    volumes:
      - ./services/api/src:/app
    command: ["fastapi", "dev", "/app/main.py", "--port", "80", "--host", "0.0.0.0"]
    # command: ["fastapi", "run", "/app/main.py", "--port", "80", "--host", "0.0.0.0"]

  elasticsearch:
    build:
      context: ./services/elastic
      dockerfile: Dockerfile
    container_name: carbo_elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
    driver: local
