version: '3'
services:

  proxy:
    image: "carbobot/proxy"
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    environment:
      - PUBLIC_HOST=localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/proxy/letsencrypt:/etc/letsencrypt
      - ./data/proxy/log:/var/log/proxy

  webapp:
    image: "carbobot/webapp"
    container_name: webapp
    hostname: webapp
    restart: unless-stopped
    environment:
      - DJANGO_DEV_SERVER=true
      - DJANGO_DEBUG=true
      - DJANGO_LOG_LEVEL=ERROR
      - WEBAPP_LOG_LEVEL=DEBUG
      - PUBLIC_HOST=http://localhost
      #- DJANGO_SECRET_KEY=
      - TELEGRAM_TOKEN=
    ports:
      - "8080:8080"
    volumes:
      - ./data/webapp/data:/data
      - ./services/webapp/code:/code # For live code changes

  search:
    image: "carbobot/search"
    container_name: search
    hostname: search
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
    ports:
      - "3000:80"
    volumes:
      - ./services/search/code:/code

  elastic:
    image: "carbobot/elastic"
    container_name: elastic
    hostname: elastic
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elastic/data:/usr/share/elasticsearch/data
