# Generated by Django 5.0.3 on 2024-07-29 20:14

import django.db.models.deletion
import webapp.core.fileds
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('main_ingredients', webapp.core.fileds.JSONField(verbose_name='Main ingredients')),
                ('typical_weight', models.IntegerField(blank=True, null=True, verbose_name='Typical weight')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('cho_ratio', models.FloatField(blank=True, null=True, verbose_name='CHO ratio')),
                ('protein_ratio', models.FloatField(blank=True, null=True, verbose_name='Protein ratio')),
                ('fiber_ratio', models.FloatField(blank=True, null=True, verbose_name='Fiber ratio')),
                ('fat_ratio', models.FloatField(blank=True, null=True, verbose_name='Fat ratio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_observations', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.food')),
            ],
        ),
    ]
