# Generated by Django 5.0.3 on 2024-11-27 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='typical_weight',
        ),
        migrations.AddField(
            model_name='food',
            name='large_serving',
            field=models.IntegerField(blank=True, null=True, verbose_name='Large serving'),
        ),
        migrations.AddField(
            model_name='food',
            name='medium_serving',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medium serving'),
        ),
        migrations.AddField(
            model_name='food',
            name='small_serving',
            field=models.IntegerField(blank=True, null=True, verbose_name='Small serving'),
        ),
        migrations.AddField(
            model_name='food',
            name='typical_serving',
            field=models.IntegerField(blank=True, null=True, verbose_name='Typical serving'),
        ),
        migrations.AlterField(
            model_name='food',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodobservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
