# Generated by Django 5.0.3 on 2025-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_food_typical_weight_food_large_serving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='large_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='Large piece'),
        ),
        migrations.AddField(
            model_name='food',
            name='medium_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medium piece'),
        ),
        migrations.AddField(
            model_name='food',
            name='small_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='Small piece'),
        ),
    ]
