# Generated by Django 5.0.3 on 2025-03-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_food_typical_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='liquid',
            field=models.BooleanField(default=False, verbose_name='Food is a liquid'),
        ),
    ]
