# Generated by Django 5.0.3 on 2025-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_food_liquid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('success', models.BooleanField()),
            ],
        ),
    ]
