#!/bin/bash

# Check if we are in the right place
if [ ! -d ./services ]; then
    echo "You must run this command from the project's root folder."
    exit 1
fi

# Init Elastic index
curl -X 'POST' \
  'http://localhost:3000/api/v1/manage/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "command": "init",
  "confirmation_code": "DEADBEEF"
}'

# Populate elastic with demo data
while IFS= read -r line
do
  curl -X 'POST' \
    'http://localhost:3000/api/v1/add/' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d "$line"
done < services/elastic/examples.json

# Populate webapp
carbobot/shell webapp "cd /code && source /env.sh && WEBAPP_LOG_LEVEL=ERROR python3 manage.py core_populate"
