#!/bin/bash

if [ "x$DJANGO_LOG_LEVEL" == "x" ]; then
    DJANGO_LOG_LEVEL="CRITICAL"
fi

if [ "x$WEBAPP_LOG_LEVEL" == "x" ]; then
    WEBAPP_LOG_LEVEL="CRITICAL"
fi

# Set DB to SQLIte in-memory
DJANGO_DB_ENGINE="django.db.backends.sqlite3"
DJANGO_DB_NAME=":memory:"

carbobot/shell webapp "export DJANGO_DB_ENGINE=$DJANGO_DB_ENGINE && export DJANGO_DB_NAME=$DJANGO_DB_NAME && cd /code && DJANGO_LOG_LEVEL=$DJANGO_LOG_LEVEL WEBAPP_LOG_LEVEL=$WEBAPP_LOG_LEVEL python3 manage.py test $@"
